bi-9120 fix bleed through issue with error message
companieshouse/psc-discrepancies.web.ch.gov.uk pull request #198
Opened 2021-09-23 12:27 UTC by ICraig-CH

- fixed bleed through issue with error message

Jira ticket: https://companieshouse.atlassian.net/browse/BI-9120

2021-09-23 13:03 UTC, ch-rfishwick approved these changes

2021-09-27 08:41 UTC, CH-JonathanBlake requested changes

2021-09-27 08:41 UTC, CH-JonathanBlake commented on server/views/report/discrepancy_details.njk
> +                    {% endif %}
Ended up indented a level to far.

2021-09-27 09:36 UTC, CH-JonathanBlake approved these changes

2021-09-27 09:36 UTC, merged