Add error page for paths which are not mapped
companieshouse/psc-discrepancies.web.ch.gov.uk pull request #71
Opened 2020-09-09 09:28 UTC by jphillips2121

If I path is not mapped for the `report-a-discrepancy` root then an error page will be displayed

Resolves: FAML-390

2020-09-09 14:11 UTC, mwejuli requested changes

2020-09-09 14:11 UTC, mwejuli commented on server/views/report/error.njk
> +{% endblock %}
Shouldn't our HTML content be similar to [this page](https://design-system.service.gov.uk/patterns/page-not-found-pages/)?

2020-09-09 14:11 UTC, mwejuli commented on server/routes/report.js
> +router.get('/report-a-discrepancy/**', (req, res) => {
perhaps this logic sits best in `server/router.js`

2020-09-09 14:16 UTC, jphillips2121 commented on server/views/report/error.njk
> +{% endblock %}
We discussed it the other day and decided to keep any error screens to the generic technical difficulties screen that we use on other services, like the one used in Java [here](https://github.com/companieshouse/common-web-java/blob/master/src/main/resources/templates/error.html)

2020-09-09 14:30 UTC, mwejuli commented on server/views/report/error.njk
> +{% endblock %}
ok, my understanding is "generic technical difficulties" is quite different from "missing page" ... but happy to approve if @sroberts2 thinks we should leave as is... 😄

2020-09-10 09:27 UTC, mwejuli approved these changes

2020-09-10 12:00 UTC, merged